## Function Resolution Helper Functions

# TODO: Implement
# Get a function based on the package name and function name
# @param package_name is the name of the package to look in
# @param function_name is the name of the function
# @return the specified function or NULL
get_function <- function(package_name = NULL, function_name) {}


## GBOV Interface Functions

# TODO: Implement; assume its a RDS file for now
# Load the Great Book of Values so that it can be used via the interface methods
# @param path is the path to the GBOV
# @return a GBOV object that can be used via the interface methods or NULL
gbov_load <- function(path) {}

# TODO: Implement
# Get the hash from the Great Book of Values at specific index
# @param GBOV is a Great Book of Values object
# @param index is a specified index of the GBOV; it must 
# @return the R value from GBOV at the specified index
gbov_get_hash(GBOV, index) {}

# TODO: Implement
# Get a random hash from the Great Book of Values
# @param GBOV is a Great Book of Values object
# @return a random R value from GBOV
gbov_get_random_hash(GBOV) {
  # idx <- next_random(0, gbov_len)
  # return the hash at index idx
  # gbov_get_value(GBOV, idx)
}

# TODO: Implement
# Get a value from the Great Book of Values based on a hash
# @param GBOV is a Great Book of Values object
# @param hash is a hash for a value in GBOV
# @return a value from GBOV based on hash
gbov_get_value(GBOV, hash) {}

# TODO: Implement
# Add a new value to the Great Book of Values
# @param GBOV is a Great Book of Value object that we add the value to
# @param value is the value being added
# @return hash value of generated by GBOV for the new value
gbov_add_value(GBOV, value) {}


## Type Identification Helper Functions

# TODO: Implement
# Get type of the input value
# @param value is a R value that signatr_typeof can make sense of
# @return the type of the value
signatr_typeof <- function(value) {}


## Run Helper Functions

# TODO: Implement
# Run a function until a specified amount of time elapsed, or until killed
# @param f is the function to be run
# @param timeout is the amount of time to run the function
run_until_timeout_or_death(timeout, f) {
  start = as.integer(Sys.time())
  while (start + timeout < as.integer(Sys.time())) {
    f
  }
}